### ISSUE TITLE
Cache invalidation of health check status

### ISSUE THREAD

**Issue by GeorgFleig** [pace/bricks#148]
The status of a broken health check (e.g. postgres not writable) is cached for too long. Even when the underlying issue is fixed, the health check reports the error for several minutes. The error was gone after restarting the pod.

**Comment by SchlottiP** [comment]
couldn't reproduce the error the way you described it. 
But I could reproduced the same error by stopping the postgres, restarting the server and restarting the postgres, the PR should fix this.
