### ISSUE TITLE
Why do you use a number for identifying routines instead of UUIDs?

### ISSUE THREAD

**Issue by daemonfire300** [pace/bricks#170]
Continuing discussion here.

/cc @Ferlonas 

https://github.com/pace/bricks/blob/ae969db1bd253d25c1cfc5ad60efd8dadf4abad5/pkg/routine/routine.go#L33

**Comment by Teelevision** [comment]
What benefit would it have?

**Comment by Ferlonas** [comment]
You can't run out of routines because there's no maximum.

**Comment by Teelevision** [comment]
There is already no maximum, as the int64 wraps around: https://play.golang.org/p/A-ZH7LnqthJ

So after around eighteen octillion four hundred forty-six septillion seven hundred forty-four sextillion seventy quintillion routines there will be routines that receive the same number again. The number is used for logging solely.
