### ISSUE TITLE
RegisterOptionalHealthCheck should have different arg order

### ISSUE THREAD

**Issue by threez** [pace/bricks#174]
### Problem

https://github.com/pace/bricks/blob/bed128afcbc9e38ac23c4cbbe9e639457b40f2a5/maintenance/health/servicehealthcheck/healthchecker.go#L156 should look more like https://github.com/pace/bricks/blob/bed128afcbc9e38ac23c4cbbe9e639457b40f2a5/maintenance/health/servicehealthcheck/healthchecker.go#L143.

Additionally, we want a func version like https://github.com/pace/bricks/blob/bed128afcbc9e38ac23c4cbbe9e639457b40f2a5/maintenance/health/servicehealthcheck/healthchecker.go#L150 should be created

**Comment by Teelevision** [comment]
Updated original comment to use permalinks.
