### ISSUE TITLE
Add log breadcrumbs to log.handleError()

### ISSUE THREAD

**Issue by Ferlonas** [pace/bricks#179]
Currently, breadcrumbs are only attached when an http request is aborted with an error or panic. Sometimes we want to use handleError to report a message to sentry without aborting the request.

Breadcrumbs should be added there as well.

**Comment by Smuerdt** [comment]
If the `context.Context` object you are passing to handleError contains a `log.Sink` this will already work out of the box. However I see a big Problem how we easily get a `log.Sink` in every "initial" context so that you can't forget it easily.

I propose to change the `log.WithContext` func in a way that it also adds a log Sink to the newly returned context. With this solution and the `log.ContextWithSink` we could promote to use these two function if a new context with logger is needed.

**Comment by Teelevision** [comment]
Adding it to `log.WithContext` does not break with backwards compatibility. Everything else still works as expected. We just get extra functionality. Right?

**Comment by Smuerdt** [comment]
Yes, but you need to be aware that you still need to use `log.ContextWithSink` at some places. For example if you want to directlty attach some values to the logger before calling `WithContext` on it.

```go
l := log.Logger().With().Str("ws_id", reqID).Logger()
ctx := log.ContextWithSink(l.WithContext(context.Background()), new(log.Sink))
```

And that resembles actually the biggest concern I have. There is no uniform and automatic way to get a log sink inside a context with a logger.

**Comment by Teelevision** [comment]
But if the original context had the sink then the child context has it, too, because the child context just uses the same output as the parent context, I would assume.

**Comment by Teelevision** [comment]
Oh, I get what you mean. We can control `log.WithContext`, but don't control `(*Logger) With Context`.

**Comment by Teelevision** [comment]
What about `log.Logger()`? Can we equip the default logger with a sink maybe?

**Comment by Teelevision** [comment]
Hm, a sink in the default logger leaves us with all the other logs that we don't want as well.

**Comment by Smuerdt** [comment]
I also thought about this but I'm not sure if this solves our problem, as we would than have a global sink for all logs...

**Comment by Teelevision** [comment]
I think this might be a bug, not a design problem. Anyway, we need more info why the breadcrumbs weren't transmitted in that case.
