### ISSUE TITLE
ScanParameters ignores characters after first whitespace

### ISSUE THREAD

**Issue by danielbalteanu96** [pace/bricks#197]
The `ScanParameters` functions uses `Sscan`, which removes characters after the first whitespace.
E.g.: for `/?filter[productName]=Super Plus`,
`fmt.Sscan(u.Query().Get("filter[productName]"), &s)` results in `s = "Super"`.
https://github.com/pace/bricks/blob/c66c8d28cbde665bb825ba19df47b323783f623c/http/jsonapi/runtime/parameters.go#L97

**Comment by Teelevision** [comment]
See https://play.golang.org/p/nwh-A5qq1Rw
