### ISSUE TITLE
Unable to generate petstore example

### ISSUE THREAD

**Issue by BertrandGouny** [pace/bricks#228]
Hello,
i wanted to try this tool that look very promissing, but i was unable to generate any code from the openapi petstore example : 
```
pb generate rest --source https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.json
2020-09-21 14:10:52 WRN Can't generate allOf, anyOf and oneOf for type "Pet"
2020/09/21 14:10:52 failed to parse response code default: strconv.Atoi: parsing "default": invalid syntax
```
```
pb generate rest --source https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.json
2020/09/21 14:14:51 failed to parse response code default: strconv.Atoi: parsing "default": invalid syntax
```
not sure what the problem is, i have no issue with [deepmap/oapi-codegen](https://github.com/deepmap/oapi-codegen) that use kin-openapi too.

**Comment by threez** [comment]
Hi @BertrandGouny,

thanks for your feedback. True, we don't allow `allOf`, `anyOf` and `oneOf` in our generator. The generator in this project
is build to best deal with APIs defined in https://jsonapi.org/ we have generator examples in the codebase: https://github.com/pace/bricks/blob/master/http/jsonapi/generator/internal/fueling/open-api.json

If you can better work with https://github.com/deepmap/oapi-codegen, then you should use it. This repository is a toolbox, in case the generator doesn't work for you, use another one. Sure, our default logging etc. wont be added in that case. That you would have to add yourself.

Does this make sense to you?
