### ISSUE TITLE
Upgrade go-pg dependency

### ISSUE THREAD

**Issue by threez** [pace/bricks#64]
### Problem

We are currently using `github.com/go-pg/pg v6.14.5` which might be outdated.

As far as I can tell the only impact this has on us is a performance one. When using the `Exists()` method on a query (e.g. `db.Model(&m).Where(...).Exists()`) go-pg [performs a regular select and checks whether the number of rows returned](https://github.com/go-pg/pg/blob/v6.14.5/orm/query.go#L1054). This is far from efficient.

### Suggested solution

Upgrade to a newer version, like v8.0.4 where [this seems to be fixed](https://github.com/go-pg/pg/blob/v8.0.4/orm/query.go#L1130).

[Changelog of v.8.0.4](https://github.com/go-pg/pg/blob/v8.0.4/CHANGELOG.md). Upgrading needs adjustments in our code:
> DB.OnQueryProcessed is replaced with DB.AddQueryHook

The format of the hook changes also.

If the impact of this upgrade is too huge, we can live with or work around the problem mentioned. But we probably have to upgrade eventually.

**Comment by daemonfire300** [comment]
Bump. Ran into the same problem when creating a new microservice with pace bricks. I think this would be beneficial.
